services:
  database:
    image: mariadb:11
    container_name: exchange-mariadb
    restart: always
    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: exchange-db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}


    volumes:
      - ./mysql_data:/var/lib/mysql
